### ISSUE TITLE
[Question] Why use asap instead of process.nextTick

### ISSUE THREAD

**Issue by Kikobeats** [npm/dezalgo#3]
As you said in your blog:

> This uses Node's synthetic deferral function: process.nextTick, which runs the supplied callback at the end of the current run-to-completion. You can also use setImmediate, but that's slightly slower. (Yes, yes, it's named badly; setImmediate is slightly less "immediate" and more "next" than nextTick, but this is an accident of history we cannot correct without a time machine.)

So, why in the implementation of this library to resolve the zalgo problem you prefer use asap library? Maybe for more crossover browser compatibility?

**Comment by Kikobeats** [comment]
Oh, correct me if is wrong, but with `process.nextTick` you just are release the callback in a different tick, but the really thing that you want to do is process the sync method in a different tick?

**Comment by chrisinajar** [comment]
@Kikobeats  After quickly reading through the source code of `asap`, it looks like it does a few things differently -- Namely, it takes priority over things like IO events in nodejs. It advertises to run the method the _soonest_ technically possible, where as nextTick gives no such guarantee, and according to the comments may or may not have some recursion problems.

Assuming this is correct, if the result which may-or-may-not-be-available uses async methods which take priority over `nextTick`, then the `async = true` line will run **after** it, causing the release of zalgo.

Read the code, perhaps you can make more sense. I rushed through it pretty quick.

Hope that helps!
