### ISSUE TITLE
Any ideas how to detect if callback is not called

### ISSUE THREAD

**Issue by tunnckoCore** [npm/dezalgo#4]
For months i'm thinking how this can be done, even is it possible? Hm, don't know but i believe it is.

And I think that `dezalgo` is the right place for this.

previous discussion https://redd.it/59fvap

Last given snippet there works, but only if you does not use dezalgo (aka if not ensured that the callback is called in the next tick).

example

```js
var once = require('once')
var dezalgo = require('dezalgo')

function task (fn) {
  var called = false
  function done (e) {
    called = true
    if (e) return console.log('err')
    console.log('ok')
  }

  fn(once(done))
  if (!called) console.log('callback is not called')
}

task(function (cb) {
  console.log('actual')
})
// signals that the `cb` is not called
```

But when we wrap the `done` with `dezalgo` we have a problem, logically. Because if it is called, it will be called in the next tick, so that `if(!called)` isn't in the correct time and the message is still outputed.

So such detection should be done in the dezalgo, because it calls the callback in the next tick. Or maybe in `once`.

**Comment by wraithgar** [comment]
closing due to age
