### ISSUE TITLE
bug in readme?

### ISSUE THREAD

**Issue by ORESoftware** [npm/dezalgo#5]
there is this
```js
    if (er) cb(er)
    cb(null, cache[arg] = data)
```

did you mean this instead

```js
    if (er) return cb(er)
    cb(null, cache[arg] = data)
```

Ryan Dahl, God among Gods, eschewed shorthand in favor of

```js
    if (er) {
       return cb(er)
    }
    cb(null, cache[arg] = data)
```

**Comment by ORESoftware** [comment]
I just noticed this line has the same problem

```js
if (cache[arg]) cb(null, cache[arg])
```

you need a return

```js
if (cache[arg]) return cb(null, cache[arg])
```

shorthand will kill us all

**Comment by codeandcats** [comment]
I thought the same thing at first, but if you follow the code you will see that this line...

```
cb = dz(cb)
```

...wraps the original callback function using this [wrappy library](https://github.com/npm/wrappy), which ensures the original function is not called more than once.

Not sure if I actually like this as it totally reads like a bug.

**Comment by ORESoftware** [comment]
yeah I see, at least add some code comments to the readme? comments are all it needs then
