### ISSUE TITLE
ERROR come out this : 'code ENOENT, errno -2 npm, syscall rename'

### ISSUE THREAD

**Issue by hanifmazlan** [npm/dezalgo#6]
i dont know what im doing wrong. i try install plugin in and suddenly this error come out. help me please. because i try so many thing. nothing help me. And it also make me cannot install any npm.

> npm ERR! path /Users/.../.../.../.../node_modules/npm/node_modules/dezalgo/node_modules/asap
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/.../.../.../.../node_modules/npm/node_modules/dezalgo/node_modules/asap' -> '/Users/.../.../.../.../node_modules/npm/node_modules/dezalgo/node_modules/.asap.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

im running on 

> $ node -v
v9.4.0
$ npm -v
5.6.0
$ ionic -v
3.19.0
$ cordova -v
8.0.0

**Comment by hanifmazlan** [comment]
i just this use this code
`-rm -rf node_modules`
`npm i`

**Comment by Fogggy** [comment]
Deleting package-lock.json and reinstalling is the only thing that worked for me

**Comment by alexmac131** [comment]
This is beyond annoying having to rm the node modules to fix this..

**Comment by ngood97** [comment]
Even if I delete my node_modules and reinstall I still get this issue :(

although my entire dezalgo folder is missing and it's asking me to rename it to dezalgo.DELETE

Update: It looks like my version of this issue was coming from having an old version of npm in my package.json

this solved my problem
https://github.com/npm/npm/issues/17444#issuecomment-361147551

**Comment by hanifmazlan** [comment]
yes, @Fogggy and @ngood97  was right. 

- delete package-lock.json

- `npm i`

**Comment by tmadison-gpsw** [comment]
`node: 8.9.4`
`npm: 5.6.0`

1. npm i (fresh install)
2. npm i (fails)
3. `rm -rf node_modules/npm`
4. npm i (works, no error)

**Comment by run1t** [comment]
@tmadison-gpsw  I have the exact same behavior than you.
But I'm on:
  `node: 9.8.0`
  `npm: 5.6.0`

Edit: Running an `npm i -g npm` to update to `5.7.1` seems to fix the error.

**Comment by crobinson42** [comment]
I had this issue too using npm v5.6.0, upgraded to 6.0.0 and now every installation works fine.

run npm i -g npm to upgrade
